### ISSUE TITLE
API call via Non-SSL HTTP is hardcoded

### ISSUE THREAD

**Issue by Maturion** [petarvujovic98/voice-rss-client#34]
In _src/browser/makeRequest.ts_ the API is explicitly called via HTTP: 
`http://${VOICE_RSS_URL}`

Would be nice to have this set to HTTPS or at least allow for manually selecting  HTTPS or HTTP.  This basically prevents this module from being used in production as HTTPS is now default almost everywhere and all modern browsers block cross origin requests from HTTPS to HTTP ressources.

**Comment by petarvujovic98** [comment]
Thank you for opening an issue about this. I will resolve this as soon as possible
